apiVersion: v1
kind: Service
metadata:
  name: employee-backend
  namespace: production
spec:
  selector:
    app: employee-backend
  ports:
    - protocol: TCP
      port: 2727
      targetPort: 2727
  type: ClusterIP