apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      containers:
        - name: employee-frontend
          image: employee-frontend:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80